dist: xenial
sudo: false

language: cpp

addons:
  apt:
    packages:
    - libboost-filesystem-dev
    - libtbb2
    - xutils-dev

before_install:
  - mkdir $HOME/downloads && cd $HOME/downloads
  # Download Belle libraries
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-b20091203-2126_181211_amd64.deb
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-cernlib2006_2006-9_amd64.deb

  # Download patches (the deb packages contain old library versions)
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/kvertexfitter.cc.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/kvertexfitter.h.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/TagV.cc.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/TagV.h.patch

  # Download binary ROOT
  - wget https://root.cern.ch/download/root_v6.14.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz

  # Download Meerkat
  - wget https://meerkat.hepforge.org/downloads/\?f\=meerkat-1.3.0.tar.gz -O meerkat-1.3.0.tar.gz

install:
  # Install Belle libraries
  - export BELLE_LIB_DIR=$HOME/bin/belle/packages/basf/belle
  - mkdir -p $HOME/bin/belle/packages/basf
  - dpkg -x belle-b20091203-2126_181211_amd64.deb $HOME/bin/belle/packages/basf
  - dpkg -x belle-cernlib2006_2006-9_amd64.deb $HOME/bin/belle/packages/basf
  - export BELLE_TOP_DIR=$BELLE_LIB_DIR/belle/b20091203_2126
  - export BELLE_RUN_DIR=$BELLE_LIB_DIR/belle/b20091203_2126/x86_64-unknown-linux-gnu/opt

  # Patch Belle libraries (the deb packages contain old library versions)
  - patch ${BELLE_TOP_DIR}/src/anal/kfitter/src/kvertexfitter.cc kvertexfitter.cc.patch
  - patch ${BELLE_TOP_DIR}/src/anal/kfitter/kfitter/kvertexfitter.h kvertexfitter.h.patch
  - patch ${BELLE_TOP_DIR}/src/anal/tagv/src/TagV.cc TagV.cc.patch
  - patch ${BELLE_TOP_DIR}/src/anal/tagv/tagv/TagV.h TagV.h.patch

  # Unpack ROOT and activate it
  - tar xzf root*.tar.gz -C ~/bin/.
  - source $HOME/bin/root/bin/thisroot.sh
  - root -b -q

  # Build Meerkat
  - mkdir -p $HOME/bin/belle/packages
  - tar xzf meerkat-1.3.0.tar.gz -C $HOME/bin/belle/packages/.
  - cd $HOME/bin/belle/packages/Meerkat
  - make
  - export ROOT_INCLUDE_PATH=$HOME/bin/belle/packages/Meerkat/inc

script:
  # These can't be compiled under ROOT 6
  # - cd ${TRAVIS_BUILD_DIR}/DSRho && xmkmf && make
  # - cd ${TRAVIS_BUILD_DIR}/DSRhoSkim && xmkmf && make
  # - cd ${TRAVIS_BUILD_DIR}/panther2TTree && xmkmf && make

  - cd ${TRAVIS_BUILD_DIR}/printTree && xmkmf && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoCPFit && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoCPFit/tests && ./run_tests.py
  - cd ${TRAVIS_BUILD_DIR}/DSRhoBackground && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoEfficiency && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoLifetime && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoLifetime/tests && ./run_tests.py
  - cd ${TRAVIS_BUILD_DIR}/DSRhoPeek && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoYield && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoYield/tests && ./run_tests.py
