#sudo: false

language: cpp

matrix:
    include:
        - python: 2
          env: PYTHON=2 ROOT=5
#        - python: 2
#          env: PYTHON=2 ROOT=6
#        - python: 3
#          env: PYTHON=3 ROOT=5
#        - python: 3
#          env: PYTHON=3 ROOT=6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xutils-dev
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-b20091203-2126_11061-2_amd64.deb
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-cernlib2006_2006-9_amd64.deb
  - sudo dpkg -i *.deb
  - export BELLE_TOP_DIR=/belle/belle/b20091203_2126
  - export BELLE_RUN_DIR=/belle/belle/b20091203_2126/x86_64-unknown-linux-gnu/opt
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/panther_manager.h.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/Panther_String.h.patch
  - patch ${BELLE_TOP_DIR}/src/util/panther/panther/panther_manager.h panther_manager.h.patch
  - patch ${BELLE_TOP_DIR}/src/util/panther/panther/Panther_String.h Panther_String.h.patch

install:
  # Conda
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - which gcc
  - gcc --version
  - which clang
  - clang --version
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC  
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${PYTHON} root=${ROOT}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  #- conda uninstall --force --yes -q sqlite libpng libx11 jpeg libtiff
  - root -b -q

before_script:
  - mkdir -p DSRhoYield/obj

script:
  #- cd ${TRAVIS_BUILD_DIR}/DSRhoYield && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoSkim && xmkmf && make
  #- python tests/test_root.py
  #- python tests/test_stl.py
