dist: trusty

language: cpp

before_install:
  - sudo apt-get -qq update

  - mkdir $HOME/downloads && cd $HOME/downloads
  # Download Belle libraries
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-b20091203-2126_11061-2_amd64.deb
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/belle-cernlib2006_2006-9_amd64.deb

  # Download patches (the deb packages contain old library versions)
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/kvertexfitter.cc.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/kvertexfitter.h.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/panther_manager.h.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/Panther_String.h.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/TagV.cc.patch
  - wget http://www-ucjf.troja.mff.cuni.cz/~cervenkov/belle_packages/TagV.h.patch

  # Download binary ROOT
  - wget https://root.cern.ch/download/root_v6.14.04.Linux-ubuntu18-x86_64-gcc7.3.tar.gz

  # Download Meerkat
  - wget https://meerkat.hepforge.org/downloads/\?f\=meerkat-1.3.0.tar.gz -O meerkat-1.3.0.tar.gz

install:
  # Install required dependencies
  - sudo apt --yes install libboost-filesystem-dev libtbb2 xutils-dev

  # Install Belle libraries
  - sudo dpkg -i *.deb
  - export BELLE_TOP_DIR=/belle/belle/b20091203_2126
  - export BELLE_RUN_DIR=/belle/belle/b20091203_2126/x86_64-unknown-linux-gnu/opt

  # Patch Belle libraries (the deb packages contain old library versions)
  - sudo patch ${BELLE_TOP_DIR}/src/anal/kfitter/src/kvertexfitter.cc kvertexfitter.cc.patch
  - sudo patch ${BELLE_TOP_DIR}/src/anal/kfitter/kfitter/kvertexfitter.h kvertexfitter.h.patch
  - sudo patch ${BELLE_TOP_DIR}/src/util/panther/panther/panther_manager.h panther_manager.h.patch
  - sudo patch ${BELLE_TOP_DIR}/src/util/panther/panther/Panther_String.h Panther_String.h.patch
  - sudo patch ${BELLE_TOP_DIR}/src/anal/tagv/src/TagV.cc TagV.cc.patch
  - sudo patch ${BELLE_TOP_DIR}/src/anal/tagv/tagv/TagV.h TagV.h.patch

  # Unpack ROOT and activate it
  - tar xzf root*.tar.gz -C ~/bin/.
  - source $HOME/bin/root/bin/thisroot.sh
  - root -b -q

  # Build Meerkat
  - mkdir -p $HOME/bin/belle/packages
  - tar xzf meerkat-1.3.0.tar.gz -C $HOME/bin/belle/packages/.
  - cd $HOME/bin/belle/packages/Meerkat
  - make
  - export ROOT_INCLUDE_PATH=$HOME/bin/belle/packages/Meerkat/inc

script:
  # These can't be compiled under ROOT 6
  # - cd ${TRAVIS_BUILD_DIR}/DSRho && xmkmf && make
  # - cd ${TRAVIS_BUILD_DIR}/DSRhoSkim && xmkmf && make
  # - cd ${TRAVIS_BUILD_DIR}/panther2TTree && xmkmf && make
  # - cd ${TRAVIS_BUILD_DIR}/printTree && xmkmf && make

  - cd ${TRAVIS_BUILD_DIR}/DSRhoCPFit && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoCPFit/tests && python tests.py
  - cd ${TRAVIS_BUILD_DIR}/DSRhoBackground && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoEfficiency && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoLifetime && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoPeek && make
  - cd ${TRAVIS_BUILD_DIR}/DSRhoYield && make
