#!/bin/bash

DIRS="$@"
STRING="Total On4S lum"

if [[ $# < 1 ]]; then
	echo "USAGE: $0 DIR(S)..."
	exit 1
fi

for DIR in $DIRS; do
	if ! [ -d $DIR ]; then
		echo "ERROR: $DIR is not a directory."
		continue
	fi

	COUNT=0
	COUNTBAD=0
	for FILE in $DIR/*.log; do
		if ! [ -f $FILE ]; then
			continue
		fi

		let 'COUNT = COUNT + 1'

		tail -n 20 $FILE | grep "$STRING" > /dev/null
		if [[ "$?" != "0" ]]; then
			echo "File $FILE doesn't contain '$STRING'"
			let 'COUNTBAD = COUNTBAD + 1'
		fi
	done

	echo "$COUNTBAD/$COUNT bad log file(s) found in $DIR"
done
