#!/bin/bash

for CHANNEL in "Kpi" "Kpipi0" "K3pi"; do
	for STREAM in $(seq 0 5); do
		mkdir -p plots/${CHANNEL}/stream${STREAM}
		./DSRhoYield ../data/${CHANNEL}/mc data/${CHANNEL}/stream${STREAM} plots/${CHANNEL}/stream${STREAM}
	done
done
