#!/bin/bash -f

shopt -s extglob

DATATYPE="on_resonance"
COLLECTED_FILE="${1}_${2}_${DATATYPE}.index"
DATAPATH_SVD1="../svd1/${DATATYPE}"
DATAPATH_SVD2="../svd2/${DATATYPE}"

# Check for arguments
if [ $# != 2 ]
    then
    echo "ERROR: Number of parameters wrong."
    echo
    echo "USAGE: check_skim_data nameprefix expXX"
    echo "where XX = 07, 09, 11, 13, 15, 17, 19, 21, 23, 25, 27, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 55, 61, 63, 65"
    echo
    exit -1
fi

if [ $2 != exp07 -a $2 != exp09 -a $2 != exp11 -a $2 != exp13 -a $2 != exp15 -a $2 != exp17 -a $2 != exp19 -a $2 != exp21 -a $2 != exp23 -a $2 != exp25 -a $2 != exp27 -a $2 != exp31 -a $2 != exp33 -a $2 != exp35 -a $2 != exp37 -a $2 != exp39 -a $2 != exp41 -a $2 != exp43 -a $2 != exp45 -a $2 != exp47 -a $2 != exp49 -a $2 != exp51 -a $2 != exp55 -a $2 != exp61 -a $2 != exp63 -a $2 != exp65 ]
    then
    echo "ERROR: Invalid experiment."
    echo
    echo "USAGE: check_skim_data nameprefix expXX"
    echo "where XX = 07, 09, 11, 13, 15, 17, 19, 21, 23, 25, 27, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 55, 61, 63, 65"
    echo
    exit -1
fi

if [ $2 != exp07 -a $2 != exp09 -a $2 != exp11 -a $2 != exp13 -a $2 != exp15 -a $2 != exp17 -a $2 != exp19 -a $2 != exp21 -a $2 != exp23 -a $2 != exp25 -a $2 != exp27 ]
	then
	DATAPATH=${DATAPATH_SVD2}
else
	DATAPATH=${DATAPATH_SVD1}
fi

rm -f ${COLLECTED_FILE}

for i in `ls ${DATAPATH} -1 | grep ${1}_${2} | grep index`; do
  echo ${DATAPATH}/$i
  cat $DATAPATH/$i >> ${COLLECTED_FILE}
done  

dbls ${COLLECTED_FILE}

exit 0
